### ISSUE TITLE
Server returns nothing when client requests games

### ISSUE THREAD

**Issue by NovaAstral** [JSH32/MineBoy#4]
I've been trying to get this setup, and when the client gets the game list from the server, the server seems to return nothing, so gamesList is nil, which crashes the client.

I can see on the server, the client connecting when it fails to get the games, so i'm not sure why its not doing anything. The server also displays the game list when it starts so its not empty.
![image](https://github.com/JSH32/MineBoy/assets/38473327/6dfde3b6-eb24-4baa-a4c1-16cb01e82ae4)
![image](https://github.com/JSH32/MineBoy/assets/38473327/1b541d45-6b32-4f85-9932-059c0d8fdcd8)

**Comment by NovaAstral** [comment]
ah! the problem is if you dont put http:// at the beginning of the http url, it will still connect but fail to actually do anything

**Comment by JSH32** [comment]
Yep, I maybe should make a "Unable to connect" message, for now im closing this
