### ISSUE TITLE
Websocket error ingame

### ISSUE THREAD

**Issue by dj8552** [JSH32/MineBoy#6]
<img width="556" alt="image" src="https://github.com/JSH32/MineBoy/assets/74438564/cca4c46a-90f2-48e1-9843-25f1283b3622">
says domain not permitted, im just using `ws://localhost:3000`. Running the server on my PC locally, is this a firewall error?

**Comment by JSH32** [comment]
Localhost is denied in the computercraft config on purpose due to security. You can change that in the configs though
https://github.com/cc-tweaked/CC-Tweaked/discussions/626
